# Generated by Django 5.2.5 on 2025-09-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_user'),
        ('main', '0002_product_user'),
    ]

    operations = [
    ]
